# Generated by Django 4.1.7 on 2023-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=256)),
                ("p_desc", models.TextField()),
                ("p_img", models.ImageField(upload_to="media")),
                ("p_price", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="RentedProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=256)),
                ("p_desc", models.TextField()),
                ("p_img", models.ImageField(upload_to="media")),
                ("p_price", models.FloatField()),
            ],
        ),
    ]
