# Generated by Django 4.1.7 on 2023-04-23 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apiApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="p_owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="p_owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="p_desc",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="p_img",
            field=models.ImageField(default=None, null=True, upload_to="media"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="p_name",
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="p_price",
            field=models.FloatField(default=None, null=True),
        ),
    ]
