# Generated by Django 4.1.7 on 2023-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_productmodel_p_owner_rentedproductmodel_p_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="r_status",
            field=models.BooleanField(default=False),
        ),
    ]
