# Generated by Django 4.1.7 on 2023-04-23 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0008_rentalrelationmodel_from_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentedproductmodel",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="apiApp.productmodel",
            ),
        ),
    ]
