# Generated by Django 4.1.7 on 2023-04-23 15:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apiApp", "0009_rentedproductmodel_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rentedproductmodel",
            unique_together={("product", "p_renter", "p_owner")},
        ),
    ]
