# Generated by Django 4.1.7 on 2023-04-25 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0011_rentedproductmodel_reject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentedproductmodel",
            name="address_ft",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="address_sec",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="email_id",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="f_name",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="from_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="l_name",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="p_number",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="postal",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="to_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rentedproductmodel",
            name="town",
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.DeleteModel(
            name="RentalRelationModel",
        ),
    ]
