# Generated by Django 4.1.7 on 2023-04-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0012_rentedproductmodel_address_ft_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="address_ft",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="address_sec",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="email_id",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="f_name",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="l_name",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="p_number",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="postal",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="town",
        ),
    ]
