# Generated by Django 4.1.7 on 2023-04-25 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0013_remove_rentedproductmodel_address_ft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentedproductmodel",
            name="from_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="rentedproductmodel",
            name="to_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
