# Generated by Django 4.1.7 on 2023-04-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0014_alter_rentedproductmodel_from_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentedproductmodel",
            name="rent_status",
            field=models.BooleanField(default=False),
        ),
    ]
