# Generated by Django 4.1.7 on 2023-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0015_rentedproductmodel_rent_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="r_status",
        ),
        migrations.RemoveField(
            model_name="rentedproductmodel",
            name="reject_status",
        ),
        migrations.AlterField(
            model_name="rentedproductmodel",
            name="rent_status",
            field=models.CharField(
                choices=[
                    ("request_raised", "Request Raised"),
                    ("request_accepted", "Request Accepted"),
                    ("rented", "Rented Successfully"),
                    ("rejected", "Rejected"),
                ],
                max_length=200,
            ),
        ),
    ]
