# Generated by Django 4.1.7 on 2023-04-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0016_remove_rentedproductmodel_r_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentedproductmodel",
            name="rent_status",
            field=models.CharField(
                choices=[
                    ("request_raised", "Request Raised"),
                    ("request_accepted", "Request Accepted"),
                    ("rented", "Rented Successfully"),
                    ("rejected", "Rejected"),
                ],
                default="request_raised",
                max_length=200,
            ),
        ),
    ]
