# Generated by Django 4.1.7 on 2023-04-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0018_productcategory_alter_productmodel_p_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentedproductmodel",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="apiApp.productmodel",
            ),
        ),
    ]
