# Generated by Django 4.1.7 on 2023-04-26 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0019_alter_rentedproductmodel_product"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rentedproductmodel",
            unique_together=set(),
        ),
    ]
